/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.practica_5_mgn;

/**
 *
 * @author davidvargas
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        mniAgregar_Usuario = new javax.swing.JMenuItem();
        mniBuscar_Usuario = new javax.swing.JMenuItem();
        mniActualizar_Usuario = new javax.swing.JMenuItem();
        mniEliminar_Usuario = new javax.swing.JMenuItem();
        mnLibro = new javax.swing.JMenu();
        mniAgregar_Libro = new javax.swing.JMenuItem();
        mniBuscar_Libro = new javax.swing.JMenuItem();
        mniActualizar_Libro = new javax.swing.JMenuItem();
        mniEliminar_Libro = new javax.swing.JMenuItem();
        mnPrestar_Devolver = new javax.swing.JMenu();
        mniPrestar_Libro = new javax.swing.JMenuItem();
        mniDevolver_Libro = new javax.swing.JMenuItem();
        mnInventario = new javax.swing.JMenu();
        Inventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        mnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PhUserBold.png"))); // NOI18N
        mnUsuario.setText("Usuario");

        mniAgregar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agregar.png"))); // NOI18N
        mniAgregar_Usuario.setText("Agregar Usuario");
        mnUsuario.add(mniAgregar_Usuario);

        mniBuscar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buscar.png"))); // NOI18N
        mniBuscar_Usuario.setText("Buscar Usuario");
        mnUsuario.add(mniBuscar_Usuario);

        mniActualizar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actualizar.png"))); // NOI18N
        mniActualizar_Usuario.setText("Actualizar Usuario");
        mnUsuario.add(mniActualizar_Usuario);

        mniEliminar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eliminar.png"))); // NOI18N
        mniEliminar_Usuario.setText("Eliminar Usuario");
        mnUsuario.add(mniEliminar_Usuario);

        jMenuBar1.add(mnUsuario);

        mnLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Libro.png"))); // NOI18N
        mnLibro.setText("Libro");

        mniAgregar_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agregar.png"))); // NOI18N
        mniAgregar_Libro.setText("Agregar Libro");
        mnLibro.add(mniAgregar_Libro);

        mniBuscar_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buscar.png"))); // NOI18N
        mniBuscar_Libro.setText("Buscar Libro");
        mnLibro.add(mniBuscar_Libro);

        mniActualizar_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actualizar.png"))); // NOI18N
        mniActualizar_Libro.setText("Actualizar Libro");
        mnLibro.add(mniActualizar_Libro);

        mniEliminar_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eliminar.png"))); // NOI18N
        mniEliminar_Libro.setText("Eliminar Libro");
        mnLibro.add(mniEliminar_Libro);

        jMenuBar1.add(mnLibro);

        mnPrestar_Devolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Prestar:Devolver.png"))); // NOI18N
        mnPrestar_Devolver.setText("Prestar / Devolver");

        mniPrestar_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Prestar.png"))); // NOI18N
        mniPrestar_Libro.setText("Prestar Libro");
        mnPrestar_Devolver.add(mniPrestar_Libro);

        mniDevolver_Libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Devolver.png"))); // NOI18N
        mniDevolver_Libro.setText("Devolver Libro");
        mnPrestar_Devolver.add(mniDevolver_Libro);

        jMenuBar1.add(mnPrestar_Devolver);

        mnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventario.png"))); // NOI18N
        mnInventario.setText("Inventario");

        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inventario-Lista.png"))); // NOI18N
        Inventario.setText("Inventario");
        mnInventario.add(Inventario);

        jMenuBar1.add(mnInventario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Inventario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnInventario;
    private javax.swing.JMenu mnLibro;
    private javax.swing.JMenu mnPrestar_Devolver;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JMenuItem mniActualizar_Libro;
    private javax.swing.JMenuItem mniActualizar_Usuario;
    private javax.swing.JMenuItem mniAgregar_Libro;
    private javax.swing.JMenuItem mniAgregar_Usuario;
    private javax.swing.JMenuItem mniBuscar_Libro;
    private javax.swing.JMenuItem mniBuscar_Usuario;
    private javax.swing.JMenuItem mniDevolver_Libro;
    private javax.swing.JMenuItem mniEliminar_Libro;
    private javax.swing.JMenuItem mniEliminar_Usuario;
    private javax.swing.JMenuItem mniPrestar_Libro;
    // End of variables declaration//GEN-END:variables
}
